on:
  pull_request:
  push:
    branches:
      - main

name: Check
jobs:
  conform:
    name: Conformance
    runs-on: ubuntu-latest
    container:
      image: golang:1
    steps:
      - name: Check out sources
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Fetch main branch for reference
        run: git fetch origin main:main
        if: github.ref_name != 'main'
      - name: Install siderolabs/conform
        run: go install github.com/siderolabs/conform/cmd/conform@latest
      - name: Run siderolabs/conform
        run: conform enforce
